// <auto-generated />
namespace VirtoCommerce.OrderModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateOrganizationWorkflow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateOrganizationWorkflow));
        
        string IMigrationMetadata.Id
        {
            get { return "201903180411284_CreateOrganizationWorkflow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
